packages:
  - "api"
  - "engine"
  - "db"
  - "ws"
  - "mm"
  - "frontend"
  - "packages/*"
allowBuilds:
  bcrypt: set this to true or false
  bufferutil: true
  esbuild: true
  unrs-resolver: true
  utf-8-validate: true
